# A player which have only those sizes allowed to claim
block-size: 9000
gap-limit: 10
allow-individual-tp: true
# Permission Nodes
admin-perm: "claimthing.admin" # Administrator
donor-perm: "claimthing.donor" # Donor flag
# Claim plugin only works on those worlds below
worlds:
  - "world"
  - "world_nether"
  - "world_the_end"
# This list removes flags players shouldnt be able to add to their clain any longer.
# use /claim update to remove existing flags
banned-flags:
  - "exit"
  - "enderdragon"
  - "ast"
  - "build"
  - "water-flow"
  - "godmode"
  - "invincible"
  - "netherportals"
  - "chunk-unload"
  - "worldedit"
  - "item-durability"
  - "exp-drops"
  - "natural-hunger-drain"
  - "fall-damage"
  - "block-place"
  - "mob-damage"
  - "block-break"
# Reserved flags for donor or admin
donor-flags:
  - fly