block-size: 9000
banned-flags:
  - "exit"
  - "enderdragon"
  - "ast"
  - "build"
  - "water-flow"
  - "godmode"
  - "invincible"
  - "netherportals"
  - "chunk-unload"
  - "worldedit"
  - "item-durability"
  - "exp-drops"
  - "natural-hunger-drain"
  - "fall-damage"
  - "block-place"
  - "mob-damage"
  - "block-break"